version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev:start
    environment:
      JWT_SECRET: "has a van"
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./lib:/app/be/lib
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
